name: Build and test core library

on:
  push:
    branches: [ 'main' ]
    paths:
      - './lib/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
  pull_request:
    branches: [ 'main' ]
    paths:
      - './lib/**'
      - 'Cargo.lock'
      - 'Cargo.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test the huskey lib
        run: cargo test --verbose
